<?xml version="1.0"?>
<definitions name="AutoCheck"
        targetNamespace="http://rms.soacrouse.unsw.edu/autocheck"
        xmlns:tns="http://rms.soacrouse.unsw.edu/autocheck"
        xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:greenslip="http://rms.soacourse.unsw.edu.au/GreenSlipService/"
        xmlns:pinkslip="http://rms.soacourse.unsw.edu.au/PinkSlipProvider/"
        >
        
         <import namespace="http://rms.soacourse.unsw.edu.au/GreenSlipService/"
            location="GreenSlipService.wsdl"/>
    <import namespace="http://rms.soacourse.unsw.edu.au/PinkSlipProvider/"
            location="PinkSlipProvider.wsdl"/>        

<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     PARTNER LINK TYPE DEFINITION
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->    
    <plnk:partnerLinkType name="GreenSlipLinkType">
        <plnk:role name="greenslip" portType="greenslip:GreenSlipService"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="PinkSlipLinkType">
        <plnk:role name="pinkslip" portType="pinkslip:PinkSlipProvider"/>
    </plnk:partnerLinkType>
    

<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     BINDING DEFINITION - Defines the message format and protocol details
     for a web service.
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <binding name="AutoCheckBinding" type="greenslip:GreenSlipService">
    	<soap:binding style="document"
    		transport="http://schemas.xmlsoap.org/soap/http" />
    	<operation name="GSCheck">
    		<soap:operation
    			soapAction="http://rms.soacrouse.unsw.edu/autocheck/process" />
    		<input>
    			<soap:body use="literal" />
    		</input>
    		<output>
    			<soap:body use="literal" />
    		</output>
    	</operation>
    </binding>

<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     SERVICE DEFINITION - A service groups a set of ports into
     a service unit.
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <service name="AutoCheckService">
    	<port name="AutoCheckPort" binding="tns:AutoCheckBinding">
    		<soap:address location="http://localhost:6060/AutoCheck" />
    	</port>
    </service>
</definitions>