package au.edu.unsw.soacourse.rms.pinkslipprovider;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-20T23:21:14.629+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "PinkSlipProvider", 
                  wsdlLocation = "file:/Users/stephen/workspace/soa/rms/PinkSlipProvider/src/main/resources/wsdl/PinkSlipProvider.wsdl",
                  targetNamespace = "http://rms.soacourse.unsw.edu.au/PinkSlipProvider/") 
public class PinkSlipProvider_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rms.soacourse.unsw.edu.au/PinkSlipProvider/", "PinkSlipProvider");
    public final static QName PinkSlipProviderSOAP = new QName("http://rms.soacourse.unsw.edu.au/PinkSlipProvider/", "PinkSlipProviderSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/stephen/workspace/soa/rms/PinkSlipProvider/src/main/resources/wsdl/PinkSlipProvider.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PinkSlipProvider_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/stephen/workspace/soa/rms/PinkSlipProvider/src/main/resources/wsdl/PinkSlipProvider.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PinkSlipProvider_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PinkSlipProvider_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PinkSlipProvider_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PinkSlipProvider_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PinkSlipProvider_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PinkSlipProvider_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns PinkSlipProvider
     */
    @WebEndpoint(name = "PinkSlipProviderSOAP")
    public PinkSlipProvider getPinkSlipProviderSOAP() {
        return super.getPort(PinkSlipProviderSOAP, PinkSlipProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PinkSlipProvider
     */
    @WebEndpoint(name = "PinkSlipProviderSOAP")
    public PinkSlipProvider getPinkSlipProviderSOAP(WebServiceFeature... features) {
        return super.getPort(PinkSlipProviderSOAP, PinkSlipProvider.class, features);
    }

}
