package au.edu.unsw.soacourse.rms.pinkslipprovider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-23T09:26:05.457+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://rms.soacourse.unsw.edu.au/PinkSlipProvider/", name = "PinkSlipProvider")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PinkSlipProvider {

    @WebResult(name = "VehicleAgeResponse", targetNamespace = "http://rms.soacourse.unsw.edu.au/PinkSlipProvider/", partName = "parameters")
    @WebMethod(operationName = "VehicleAge", action = "http://rms.soacourse.unsw.edu.au/PinkSlipProvider/VehicleAge")
    public VehicleAgeResponse vehicleAge(
        @WebParam(partName = "parameters", name = "VehicleAgeRequest", targetNamespace = "http://rms.soacourse.unsw.edu.au/PinkSlipProvider/")
        VehicleAgeRequest parameters
    ) throws DriverNotFoundFaultException, DataAccessFaultException;

    @WebResult(name = "PSCheckResponse", targetNamespace = "http://rms.soacourse.unsw.edu.au/PinkSlipProvider/", partName = "parameters")
    @WebMethod(operationName = "PSCheck", action = "http://rms.soacourse.unsw.edu.au/PinkSlipProvider/PSCheck")
    public PSCheckResponse psCheck(
        @WebParam(partName = "parameters", name = "PSCheckRequest", targetNamespace = "http://rms.soacourse.unsw.edu.au/PinkSlipProvider/")
        PSCheckRequest parameters
    ) throws DriverNotFoundFaultException, DataAccessFaultException;
}
