package au.edu.unsw.soacourse.rms.greenslipservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-23T09:39:42.446+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "GreenSlipService", 
                  wsdlLocation = "file:/Users/stephen/workspace/soa/rms/GreenSlipService/src/main/resources/wsdl/GreenSlipService.wsdl",
                  targetNamespace = "http://rms.soacourse.unsw.edu.au/GreenSlipService/") 
public class GreenSlipService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rms.soacourse.unsw.edu.au/GreenSlipService/", "GreenSlipService");
    public final static QName GreenSlipServiceSOAP = new QName("http://rms.soacourse.unsw.edu.au/GreenSlipService/", "GreenSlipServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/stephen/workspace/soa/rms/GreenSlipService/src/main/resources/wsdl/GreenSlipService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GreenSlipService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/stephen/workspace/soa/rms/GreenSlipService/src/main/resources/wsdl/GreenSlipService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GreenSlipService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GreenSlipService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreenSlipService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreenSlipService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreenSlipService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreenSlipService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns GreenSlipService
     */
    @WebEndpoint(name = "GreenSlipServiceSOAP")
    public GreenSlipService getGreenSlipServiceSOAP() {
        return super.getPort(GreenSlipServiceSOAP, GreenSlipService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GreenSlipService
     */
    @WebEndpoint(name = "GreenSlipServiceSOAP")
    public GreenSlipService getGreenSlipServiceSOAP(WebServiceFeature... features) {
        return super.getPort(GreenSlipServiceSOAP, GreenSlipService.class, features);
    }

}
