
package au.edu.unsw.soacourse.rms.greenslipservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-20T17:38:54.133+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "GSCheckFault", targetNamespace = "http://rms.soacourse.unsw.edu.au/GreenSlipService/")
public class GSCheckFault_Exception extends Exception {
    
    private au.edu.unsw.soacourse.rms.greenslipservice.GSCheckFault gsCheckFault;

    public GSCheckFault_Exception() {
        super();
    }
    
    public GSCheckFault_Exception(String message) {
        super(message);
    }
    
    public GSCheckFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GSCheckFault_Exception(String message, au.edu.unsw.soacourse.rms.greenslipservice.GSCheckFault gsCheckFault) {
        super(message);
        this.gsCheckFault = gsCheckFault;
    }

    public GSCheckFault_Exception(String message, au.edu.unsw.soacourse.rms.greenslipservice.GSCheckFault gsCheckFault, Throwable cause) {
        super(message, cause);
        this.gsCheckFault = gsCheckFault;
    }

    public au.edu.unsw.soacourse.rms.greenslipservice.GSCheckFault getFaultInfo() {
        return this.gsCheckFault;
    }
}
